[build]
  command = "pip install -r requirements.txt"
  publish = "web/static"
  functions = "netlify/functions"

[dev]
  command = "python app.py"
  port = 5000
  publish = "web/static"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/api/search"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 